server:
  port: 8081

spring:
  application:
    name: alert-service
  
  datasource:
    url: jdbc:mysql://localhost:3306/alert_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  exchange-created: incident.created.exchange
  queue-incident-created: alert-service.created.queue
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/