server:
  port: ${SERVICE_PORT}

spring:
  application:
    name: auth-service
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            domain: .etf.unibl.org
            scope:
              - openid
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  key: ${JWT_KEY}
  validity: ${JWT_VALIDITY}

cookie:
  domain: ${COOKIE_DOMAIN}
  name: IS_MS
rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: guest
    password: guest
    exchange: user-exchange
    queueAdminOrModeratorCreated: admin-or-moderator-created-queue
    queueRoleUpdated: role-updated-queue
    queueUserCreated: user-created-queue
    routingKeyAdminOrModeratorCreated: admin.moderator.created
    routingKeyUserCreated: user.created
    routingKeyRoleUpdated: role.updated
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

