server:
  port: 8082

spring:
  application:
    name: moderation-service
  datasource:
    url: jdbc:mysql://localhost:3306/moderation_db
    username: "{cipher}f187b26dd1ffc93145e2b4ff6b9f2443abbefa7f5eae2841bbdc6a6c0ecbf26a"
    password: "{cipher}703aef4b8e54aed68f1225cfc0b26b3efb7d8b03521870f4a1b2abf9b70a6647"
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  exchange: incident-exchange
  queue-incident-created: incident-created-queue
  queue-status-updated: status-updated-queue
  routing-key-incident-created: incident.created
  routing-key-status-updated: incident.status.updated
