server:
  port: 8082

spring:
  application:
    name: moderation-service
  datasource:
    url: jdbc:mysql://localhost:3306/moderation_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  exchange: incident-exchange
  queue-incident-created: incident-created-queue
  queue-status-updated: status-updated-queue
  routing-key-incident-created: incident.created
  routing-key-status-updated: incident.status.updated

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/