server:
  port: 0

spring:
  application:
    name: moderation-service
  datasource:
    url: jdbc:mysql://mysql:3307/moderation_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

rabbitmq:
  host: rabbitmq
  port: 5672
  username: guest
  password: guest
  exchange: incident-exchange
  queue-incident-created: incident-created-queue
  queue-status-updated: status-updated-queue
  routing-key-incident-created: incident.created
  routing-key-status-updated: incident.status.updated

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      instanceId: ${spring.application.name}:${random.uuid}

# Zipkin
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411