server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: incident-service
          uri: lb://incident-service
          predicates:
            - Path=/incident-service/**
          filters:
            - StripPrefix=1

        - id: moderation-service
          uri: lb://moderation-service
          predicates:
            - Path=/moderation-service/**
          filters:
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/