server:
  port: 8080

spring:
  application:
    name: gateway-service

    cloud:
      gateway:
        routes:
          - id: incident-service
            uri: lb://incident-service
            predicates:
              - Path=/incident-service/**
            filters:
              - StripPrefix=1

          - id: moderation-service
            uri: lb://moderation-service
            predicates:
              - Path=/moderation-service/**
            filters:
              - StripPrefix=1