server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: incident-service
          uri: http://localhost:8081
          predicates:
            - Path=/incident/**
          filters:
            - StripPrefix=1

        - id: moderation-service
          uri: http://localhost:8082
          predicates:
            - Path=/moderation/**
          filters:
            - StripPrefix=1

        - id: auth-service
          uri: http://localhost:8083
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: http://localhost:8084
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

        - id: analytics-service
          uri: http://localhost:8085
          predicates:
            - Path=/analytics/**
          filters:
            - StripPrefix=1

        - id: alert-service
          uri: http://localhost:8086
          predicates:
            - Path=/alert/**
          filters:
            - StripPrefix=1

        - id: nlp-service
          uri: http://localhost:8087
          predicates:
            - Path=/nlp/**
          filters:
            - StripPrefix=1

        - id: translation-service
          uri: http://localhost:8088
          predicates:
            - Path=/translation/**
          filters:
            - StripPrefix=1

        - id: map-service
          uri: http://localhost:8089
          predicates:
            - Path=/map/**
          filters:
            - StripPrefix=1
