server:
  port: 8081

spring:
  application:
    name: incident-service

  datasource:
    url: jdbc:mysql://localhost:3306/incident_db
    username: "{cipher}01aff1fdca5d3154c8c3a9a54736f74720111ac31f4ce14d5949ad318921f5ee"
    password: "{cipher}30b4288b30b2795c84b8291accda94902c84f7b5e108e112076b4c4ca449874d"

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# Uncomment if using AWS Secrets Manager
#  config:
#    import: optional:aws-secretsmanager:prod/incident-service-s3

aws:
  region: eu-north-1
  bucketName: vanja-djenadija-incident-service-images

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  exchange: incident-exchange
  queue-incident-created: incident-created-queue
  queue-status-updated: status-updated-queue
  routing-key-incident-created: incident.created
  routing-key-status-updated: incident.status.updated
